Fahmi Nanda Saputro 1103200203

1. Melakukan import Pytorch

In [10]:
import torch
torch.__version__

'2.1.0+cu121'

2. Membuat Tensor Scalar

In [11]:
#membuat scalar yang merupakan Single Number di tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [13]:
# Scalar Vector
vector = torch.tensor([4, 5])
vector

tensor([4, 5])

In [14]:
# Cek dimensi nomor vector
vector.ndim

1

In [15]:
#cek bentuk dari vector
vector.shape

torch.Size([2])

In [16]:
#melihat matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
# Cek dimensi nomor vector
MATRIX.ndim

2

In [18]:
#membuat Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [20]:
#cek bentuk tensor
TENSOR.shape

torch.Size([1, 3, 3])

3. Membuat Random Tensor

In [21]:
#membuat random tensor dengan size (4,6)
random_tensor = torch.rand(size=(4, 6))
random_tensor, random_tensor.dtype

(tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593],
         [0.7204, 0.0731, 0.9699, 0.1078, 0.8829, 0.4132],
         [0.7572, 0.6948, 0.5209, 0.5932, 0.8797, 0.6286],
         [0.7653, 0.1132, 0.8559, 0.6721, 0.6267, 0.5691]]),
 torch.float32)

In [22]:
#membuat random tensor dengan size (243,170,2)
random_image_size_tensor = torch.rand(size=(243,170,2))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([243, 170, 2]), 3)

4. Membuat Zero dan Ones

In [23]:
#membuat tensor dengan semuanya nol
zeros = torch.zeros(size=(4, 6))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]),
 torch.float32)

In [24]:
#membuat tensor dengan semuanya satu
ones = torch.ones(size=(4, 6))
ones, ones.dtype

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]),
 torch.float32)

5. Membuat Range Tensors

In [25]:
#membuat range dan tensor

# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=2)
zero_to_ten

<ipython-input-25-f953a583fda1>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 2, 4, 6, 8])

In [26]:
#membuat range tensor menggunakan angka nol
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0])

6. Tensor Datatypes

In [27]:
#tensor data type

# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [28]:
#membuat tensor dengan float 16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

7. Mencari info di Tensors

In [29]:
#membuat tensor
some_tensor = torch.rand(3, 4)

#mencari detail info
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.5038, 0.4172, 0.4096, 0.7267],
        [0.2575, 0.0782, 0.0368, 0.0382],
        [0.3828, 0.3983, 0.8709, 0.1898]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


8. Manipulasi Tensor dengan Operasi Basic

In [30]:
#membuat value tensor dan menambahkan angka
tensor = torch.tensor([2, 4, 6])
tensor + 10

tensor([12, 14, 16])

In [31]:
#lalu dikali 15
tensor * 15

tensor([30, 60, 90])

In [32]:
#Tensors tidak berubah kecuali di reassigned
tensor

tensor([2, 4, 6])

In [33]:
#melakukan pengurangan dan reassign
tensor = tensor - 10
tensor

tensor([-8, -6, -4])

In [34]:
#melakukan penjumlahan dan reassign
tensor = tensor + 10
tensor

tensor([2, 4, 6])

In [35]:
#menggunakan torch function
torch.multiply(tensor, 15)

tensor([30, 60, 90])

In [36]:
#original tensor masih belum berubah
tensor

tensor([2, 4, 6])

In [37]:
#bisa menggunakan  * untuk melakukan perkalian
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([2, 4, 6]) * tensor([2, 4, 6])
Equals: tensor([ 4, 16, 36])


9. Perkalian Matrix

In [38]:
#membuat tensor
import torch
tensor = torch.tensor([2, 4, 6])
tensor.shape

torch.Size([3])

In [39]:
# Element-wise matrix multiplication
tensor * tensor

tensor([ 4, 16, 36])

In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(56)

In [41]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(56)

In [42]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.48 ms, sys: 0 ns, total: 1.48 ms
Wall time: 1.46 ms


tensor(56)

In [43]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 78 µs, sys: 20 µs, total: 98 µs
Wall time: 67.2 µs


tensor(56)

10. Error yang biasa terjadi di deep learning

In [44]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [45]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [46]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [47]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [48]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [49]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


11. Mencari min, max, mean, sum (aggregation)

In [50]:
# Membuat tensor
x = torch.arange(0, 125, 5)
x

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120])

In [51]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 120
Mean: 60.0
Sum: 1500


In [52]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(120), tensor(0), tensor(60.), tensor(1500))

12. Positial Min / Max

In [53]:
# Create a tensor
tensor = torch.arange(15, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([15, 25, 35, 45, 55, 65, 75, 85, 95])
Index where max value occurs: 8
Index where min value occurs: 0


13. Mengganti Tensor Datatype

In [54]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [55]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [56]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

14. Melakukan Reshaping, stacking, squeezing dan unsqueezing

In [63]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [66]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [67]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [68]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [69]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [70]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


15. Indexing (menyleksi data dari tensor)

In [71]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [73]:
#bisa menambahkan : untuk menspesifik "semua value di dimensi" lalau menggunakan koma untuk menambahkan dimensi lain

# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [74]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [75]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [76]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

16. Pytorch Tensor dan Numpy

In [77]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(2.0, 10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [78]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [79]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [80]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

17. Reproducibilitas (membuat untuk mengambil random dari beberapa random)

In [81]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(4, 5)
random_tensor_B = torch.rand(4, 5)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8660, 0.2001, 0.7926, 0.1140, 0.6855],
        [0.0086, 0.3588, 0.9211, 0.8627, 0.8223],
        [0.5248, 0.5881, 0.2746, 0.3791, 0.2975],
        [0.6450, 0.0163, 0.9160, 0.5888, 0.8403]])

Tensor B:
tensor([[0.4761, 0.7140, 0.4644, 0.6362, 0.8892],
        [0.1317, 0.7164, 0.2706, 0.6560, 0.6614],
        [0.3648, 0.1490, 0.8693, 0.0294, 0.5449],
        [0.0794, 0.2313, 0.2927, 0.3386, 0.3708]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [82]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(4, 5)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(4, 5)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739, 0.2666, 0.6274]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739, 0.2666, 0.6274]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

18. Menjalankan Tensor di GPU

In [83]:
!nvidia-smi

Thu Jan  4 12:08:43 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P0              29W /  70W |    137MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [84]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [85]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [86]:
# Count number of devices
torch.cuda.device_count()

1

In [87]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [88]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: ignored

In [89]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [90]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [91]:
#Exercise
import torch

torch.manual_seed(0)
random_tensor = torch.rand((7, 7))


In [92]:
torch.manual_seed(0)
second_tensor = torch.rand((1, 7))
result = torch.mm(random_tensor, second_tensor.t())  # Transpose the second tensor


In [93]:
torch.manual_seed(0)
random_tensor = torch.rand((7, 7))
second_tensor = torch.rand((1, 7))
result = torch.mm(random_tensor, second_tensor.t())


In [94]:
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)

In [95]:
torch.manual_seed(1234)
if torch.cuda.is_available():
    tensor_gpu1 = torch.rand((2, 3)).cuda()
    tensor_gpu2 = torch.rand((2, 3)).cuda()

In [96]:
result_gpu = torch.mm(tensor_gpu1, tensor_gpu2.t())  # Adjust shapes if needed


In [97]:
max_value = torch.max(result_gpu)
min_value = torch.min(result_gpu)

In [98]:
max_index = torch.argmax(result_gpu)
min_index = torch.argmin(result_gpu)

In [99]:
torch.manual_seed(7)
tensor_4d = torch.rand((1, 1, 1, 10))
tensor_1d = tensor_4d.squeeze()
print("Original Tensor:", tensor_4d, "Shape:", tensor_4d.shape)
print("Modified Tensor:", tensor_1d, "Shape:", tensor_1d.shape)

Original Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) Shape: torch.Size([1, 1, 1, 10])
Modified Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) Shape: torch.Size([10])
